name: Bug report
description: Create a report to help us improve.
title: '[Bug]: '
labels: ['bug']
body:
  - type: textarea
    id: what-went-wrong
    attributes:
      label: What went wrong?
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true
