blank_issues_enabled: false
contact_links:
  - name: '#bug-reports Discord channel'
    url: https://discord.gg/SnxgHs3wEc
    about: If you are not sure whether you encountered a bug or not, feel free to join our Discord server and tell us about it.
