name: Feature request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['feature']
body:
  - type: textarea
    id: describe-your-idea
    attributes:
      label: Describe your idea
    validations:
      required: true
