name: ci
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          USE_MINGW: 0
          TARGET: java/build/libio_github_bernhardfritz_p8g_Sketch.dylib
        - os: ubuntu-latest
          USE_MINGW: 0
          TARGET: java/build/libio_github_bernhardfritz_p8g_Sketch.so
        - os: ubuntu-latest
          USE_MINGW: 1
          TARGET: java/build/io_github_bernhardfritz_p8g_Sketch.dll
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd java
          if [ "${{ matrix.USE_MINGW }}" = 1 ]; then
            sudo apt-get install -y mingw-w64
            make CC=x86_64-w64-mingw32-gcc OS=Windows_NT JNI_MD_DIR=${JAVA_HOME}/include/linux
          else
            make
          fi
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ${{ matrix.TARGET }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - run: |
          mv build java
          cd java
          make build/p8g.jar
          rm -rf build/io
          rm -f build/io_github_bernhardfritz_p8g_Sketch.dll build/libio_github_bernhardfritz_p8g_Sketch.dylib build/libio_github_bernhardfritz_p8g_Sketch.so
          zip -jr p8g.zip build ../c/p8g.h ../c/p8g.html ../c/p8g.wasm
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: java/p8g.zip