name: Test deployment

on:
  pull_request:
    branches:
      - 'master'
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: docs/yarn.lock

      - name: Install dependencies
        working-directory: docs
        run: yarn install --frozen-lockfile
      - name: Test build website
        working-directory: docs
        run: yarn build